In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [7]:
independent=dataset[["Age","EstimatedSalary","Gender_Male"]]
dependent=dataset["Purchased"]

In [8]:
dependent.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [20]:
#split into training set and test
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [24]:
# Step 5: Feature Scaling (Important for SVM)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
svc = SVC()

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.1, 0.01]
}

grid = GridSearchCV(
    estimator=svc,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [30]:
grid.fit(X_train, y_train)

# Step 2: Then access results
re = grid.cv_results_

print("The classification value for best parameter {}:"
      .format(grid.best_params_))

table = pd.DataFrame.from_dict(re)
table

The classification value for best parameter {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}:

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003760,0.000510,0.002419,0.000311,0.1,scale,linear,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}",0.777778,0.773585,0.716981,0.924528,0.867925,0.812159,0.074115,34
1,0.004367,0.001069,0.003526,0.000458,0.1,scale,rbf,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}",0.851852,0.849057,0.792453,0.981132,0.962264,0.887352,0.072304,11
2,0.003779,0.000556,0.002419,0.000342,0.1,scale,poly,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'poly'}",0.796296,0.754717,0.679245,0.867925,0.811321,0.781901,0.062849,40
3,0.004038,0.000582,0.002860,0.000534,0.1,auto,linear,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}",0.777778,0.773585,0.716981,0.924528,0.867925,0.812159,0.074115,34
4,0.007139,0.002155,0.006324,0.002799,0.1,auto,rbf,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}",0.851852,0.849057,0.792453,0.981132,0.962264,0.887352,0.072304,11
5,0.005343,0.001739,0.003435,0.000440,0.1,auto,poly,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'poly'}",0.796296,0.754717,0.679245,0.849057,0.811321,0.778127,0.057946,41
6,0.004285,0.000873,0.004621,0.002455,0.1,0.1,linear,"{'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}",0.777778,0.773585,0.716981,0.924528,0.867925,0.812159,0.074115,34
7,0.005264,0.000801,0.004441,0.000798,0.1,0.1,rbf,"{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}",0.796296,0.773585,0.716981,0.924528,0.867925,0.815863,0.072755,33
8,0.005365,0.002061,0.002825,0.000337,0.1,0.1,poly,"{'C': 0.1, 'gamma': 0.1, 'kernel': 'poly'}",0.648148,0.660377,0.641509,0.641509,0.641509,0.646611,0.007348,43
9,0.004982,0.001882,0.003099,0.001258,0.1,0.01,linear,"{'C': 0.1, 'gamma': 0.01, 'kernel': 'linear'}",0.777778,0.773585,0.716981,0.924528,0.867925,0.812159,0.074115,34
10,0.007687,0.002374,0.006054,0.002687,0.1,0.01,rbf,"{'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}",0.648148,0.660377,0.641509,0.641509,0.641509,0.646611,0.007348,43
11,0.005849,0.001823,0.003904,0.000917,0.1,0.01,poly,"{'C': 0.1, 'gamma': 0.01, 'kernel': 'poly'}",0.648148,0.660377,0.641509,0.641509,0.641509,0.646611,0.007348,43
12,0.008112,0.001545,0.004358,0.001104,1.0,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.796296,0.773585,0.716981,0.924528,0.905660,0.823410,0.079416,29
13,0.004972,0.001381,0.004365,0.002373,1.0,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.888889,0.886792,0.849057,0.943396,0.962264,0.906080,0.041154,1
14,0.004972,0.002585,0.005972,0.005690,1.0,scale,poly,"{'C': 1, 'gamma': 'scale', 'kernel': 'poly'}",0.814815,0.811321,0.735849,0.943396,0.830189,0.827114,0.066725,27
15,0.003488,0.001009,0.002429,0.001007,1.0,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.796296,0.773585,0.716981,0.924528,0.905660,0.823410,0.079416,29
16,0.007745,0.002138,0.006938,0.001347,1.0,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.888889,0.886792,0.849057,0.943396,0.962264,0.906080,0.041154,1
17,0.004781,0.001956,0.003220,0.001722,1.0,auto,poly,"{'C': 1, 'gamma': 'auto', 'kernel': 'poly'}",0.814815,0.811321,0.735849,0.943396,0.830189,0.827114,0.066725,27
18,0.003001,0.000107,0.001786,0.000043,1.0,0.1,linear,"{'C': 1, 'gamma': 0.1, 'kernel': 'linear'}",0.796296,0.773585,0.716981,0.924528,0.905660,0.823410,0.079416,29
19,0.003190,0.000096,0.002567,0.000097,1.0,0.1,rbf,"{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}",0.888889,0.849057,0.849057,0.943396,0.962264,0.898532,0.047039,8
20,0.004875,0.001598,0.004060,0.002940,1.0,0.1,poly,"{'C': 1, 'gamma': 0.1, 'kernel': 'poly'}",0.722222,0.716981,0.641509,0.754717,0.754717,0.718029,0.041391,42
21,0.003014,0.000141,0.001841,0.000061,1.0,0.01,linear,"{'C': 1, 'gamma': 0.01, 'kernel': 'linear'}",0.796296,0.773585,0.716981,0.924528,0.905660,0.823410,0.079416,29
22,0.006380,0.003170,0.005718,0.001938,1.0,0.01,rbf,"{'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}",0.759259,0.754717,0.698113,0.886792,0.867925,0.793361,0.072135,39
23,0.007473,0.000475,0.005039,0.000208,1.0,0.01,poly,"{'C': 1, 'gamma': 0.01, 'kernel': 'poly'}",0.648148,0.660377,0.641509,0.641509,0.641509,0.646611,0.007348,43
24,0.004865,0.001313,0.002684,0.001031,10.0,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
25,0.006055,0.001886,0.005117,0.001757,10.0,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.870370,0.886792,0.867925,0.943396,0.943396,0.902376,0.034116,3
26,0.010319,0.000754,0.004840,0.000469,10.0,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.814815,0.811321,0.792453,0.924528,0.905660,0.849755,0.054218,13
27,0.005262,0.002299,0.002337,0.001075,10.0,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
28,0.004751,0.002121,0.004556,0.002180,10.0,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.870370,0.886792,0.867925,0.943396,0.943396,0.902376,0.034116,3
29,0.004645,0.002140,0.002468,0.001236,10.0,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.814815,0.811321,0.792453,0.924528,0.905660,0.849755,0.054218,13
30,0.010048,0.001137,0.004257,0.000476,10.0,0.1,linear,"{'C': 10, 'gamma': 0.1, 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
31,0.006796,0.001021,0.005224,0.000708,10.0,0.1,rbf,"{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}",0.888889,0.867925,0.849057,0.943396,0.962264,0.902306,0.043545,7
32,0.007834,0.001882,0.006094,0.001948,10.0,0.1,poly,"{'C': 10, 'gamma': 0.1, 'kernel': 'poly'}",0.814815,0.773585,0.716981,0.905660,0.811321,0.804472,0.061647,38
33,0.010415,0.001733,0.004470,0.000334,10.0,0.01,linear,"{'C': 10, 'gamma': 0.01, 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
34,0.008085,0.001000,0.006830,0.000578,10.0,0.01,rbf,"{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}",0.814815,0.811321,0.735849,0.943396,0.905660,0.842208,0.073867,17
35,0.007399,0.002143,0.005167,0.000580,10.0,0.01,poly,"{'C': 10, 'gamma': 0.01, 'kernel': 'poly'}",0.648148,0.660377,0.641509,0.641509,0.641509,0.646611,0.007348,43
36,0.026558,0.002395,0.005173,0.001598,100.0,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
37,0.009716,0.002571,0.005223,0.002202,100.0,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.870370,0.886792,0.867925,0.943396,0.943396,0.902376,0.034116,3
38,0.051545,0.025410,0.004085,0.000833,100.0,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.833333,0.792453,0.773585,0.924528,0.905660,0.845912,0.059996,15
39,0.019908,0.001122,0.003493,0.000502,100.0,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
40,0.011111,0.001867,0.005116,0.000394,100.0,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.870370,0.886792,0.867925,0.943396,0.943396,0.902376,0.034116,3
41,0.034720,0.006432,0.004489,0.000874,100.0,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.833333,0.792453,0.773585,0.924528,0.905660,0.845912,0.059996,15
42,0.019715,0.004030,0.003527,0.000729,100.0,0.1,linear,"{'C': 100, 'gamma': 0.1, 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
43,0.008565,0.001529,0.004975,0.000884,100.0,0.1,rbf,"{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}",0.888889,0.886792,0.849057,0.943396,0.924528,0.898532,0.032763,8
44,0.007276,0.001393,0.003945,0.001438,100.0,0.1,poly,"{'C': 100, 'gamma': 0.1, 'kernel': 'poly'}",0.833333,0.811321,0.735849,0.924528,0.905660,0.842138,0.068041,18
45,0.023639,0.003071,0.003619,0.001011,100.0,0.01,linear,"{'C': 100, 'gamma': 0.01, 'kernel': 'linear'}",0.796296,0.792453,0.716981,0.924528,0.905660,0.827184,0.077381,19
46,0.007633,0.000787,0.003900,0.001222,100.0,0.01,rbf,"{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}",0.870370,0.849057,0.830189,0.943396,0.962264,0.891055,0.052358,10
47,0.008760,0.001690,0.004718,0.000104,100.0,0.01,poly,"{'C': 100, 'gamma': 0.01, 'kernel': 'poly'}",0.648148,0.660377,0.641509,0.641509,0.641509,0.646611,0.007348,43

In [31]:
y_pred = grid.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1])

In [32]:
print("Best Parameters:", grid.best_params_)

Best Parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}

In [33]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [34]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9104477611940298
Confusion Matrix:
 [[77  8]
 [ 4 45]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.91      0.93        85
           1       0.85      0.92      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.91      0.91       134
weighted avg       0.91      0.91      0.91       134